### ISSUE TITLE
Typo in `Options` module

### ISSUE THREAD

**Issue by sbennett33** [sascha-wolf/knigge#2]
There is a typo in the `Options` module which prevents this library from working properly.

https://github.com/sascha-wolf/knigge/blob/1fb2f223b3818a1a674878ae4552a7e413d3bbf9/lib/knigge/options.ex#L83

You are trying to read `opt_app` from the options list instead of `otp_app`.

**Comment by sascha-wolf** [comment]
Damn, as it turned out the covering test didn’t run because I named it incorrectly. That's my punishment for not doing strictly TDD. 😄 

It's fixed in 1.0.2, thanks for the report!
