### ISSUE TITLE
Exclude Bunt dependency from the runtime

### ISSUE THREAD

**Issue by samuel-uniris** [sascha-wolf/knigge#26]
Hello.

I'm facing some issue to integrate Knigge.
Bunt is a dependency used for the CLI, however, when you have to do some release upgrades, SASL `release_handler` crash because there is no top supervisor for the `bunt` application. 
(See other discussion regarding this also: https://github.com/bitwalker/exrm/issues/183)

An idea would be to tag the `bunt` dependency only in dev or exclude it from the runtime.

**Comment by sascha-wolf** [comment]
Fixed in [version 1.4.1](https://github.com/sascha-wolf/knigge/releases/tag/v1.4.1)
