### ISSUE TITLE
Add a .formattter.exs which exports defdefault as locals_without_parens

### ISSUE THREAD

**Issue by sascha-wolf** [sascha-wolf/knigge#6]
Currently the formatter adds parens around a one-line `defdefault`; this could be disabled by adding `defdefault: 2` as an exported `locals_without_parents`.

**Comment by herminiotorres** [comment]
hi, @sascha-wolf I open the `.formatter.exs` and the file reflects would you desire right now.

could you explain a little bit more...

**Comment by sascha-wolf** [comment]
@herminiotorres thanks for the interest. It seems I've already fixed this issue a while ago in 43fcabcc276565d72c1ae915a1a55e809806096b. So there's nothing to do here.

Sorry for the confusion!
